apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: piyush67sharma/auth_service:1.7  # Replace with your Docker Hub image
        ports:
        - containerPort: 8080  # Adjust port based on your app
        env:
        - name : DB_HOST
          value: myapp.chcq006um4dc.ap-south-1.rds.amazonaws.com
        - name : DB_USER
          value : postgres
        - name : DB_PASSWORD
          value : postgres981
        - name : DB_NAME
          value : myapp
        - name : DB_SSLMODE
          value : require
      # If private image, uncomment below and use the secret
      imagePullSecrets:
      - name: dockerhub-secret