apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server
  labels:
    app: main-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
      - name: main-server
        image: piyush67sharma/main_server:1.4  # Replace with your Docker Hub image
        ports:
        - containerPort: 8080  # Adjust port based on your app
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_SSL_MODE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_SSL_MODE
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: main-server-config  # Referring to the ConfigMap name
              key: HTTP_PORT  # Key from the ConfigMap
      # If private image, uncomment below and use the secret
      imagePullSecrets:
      - name: regcred