version: '3.8'

services:
  auth-service:
    build:
      context: ./auth_service   # Path to the auth_service folder
      dockerfile: Dockerfile.local  
    container_name: auth-service_local
    ports:
      - "8081:8081"  # Mapping the port inside the container to your local machine
    volumes:
      - ./auth_service:/app 
    networks:
      - microservices-network
    env_file:
      - .env
    environment:
      - GRPC_PORT=50051
      - HTTP_PORT=8081
  notification-service:
    build:
      context: ./notification_service   # Path to the auth_service folder
      dockerfile: Dockerfile.local  
    container_name: notification-service_local
    ports:
      - "8082:8082"  # Mapping the port inside the container to your local machine
    volumes:
      - ./auth_service:/app 
    networks:
      - microservices-network
    env_file:
      - .env
    environment:
      - GRPC_PORT=50052
      - HTTP_PORT=8082

  main-server:
    build:
      context: ./main_server  # Path to the main_server folder
      dockerfile: Dockerfile.local  
    container_name: main-server_local
    ports:
      - "8080:8080"  # Mapping the port inside the container to your local machine
    networks:
      - microservices-network
    depends_on:
      - auth-service  # main-server depends on auth-service
    env_file:
      - .env
    volumes:
      - ./main_server:/app 
    environment:
      - GRPC_PORT=50050
      - HTTP_PORT=8080
      - AUTH_SERVICE_HTTP_URL=http://auth-service:8081
      - AUTH_SERVICE_GRPC_URL=auth-service:50051
      - NOTIFICATION_SERVICE_HTTP_URL=http://auth-service:8082
      - NOTIFICATION_SERVICE_GRPC_URL=auth-service:50052
      

networks:
  microservices-network:
    driver: bridge
