apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: piyush67sharma/auth_service:1.17  # Replace with your Docker Hub image
        ports:
        - containerPort: 8080  # Adjust port based on your app
        - containerPort: 50051
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_SSL_MODE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_SSL_MODE
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config  # Referring to the ConfigMap name
              key: GRPC_PORT  # Key from the ConfigMap
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: auth-service-config  # Referring to the ConfigMap name
              key: HTTP_PORT  # Key from the ConfigMap
      # If private image, uncomment below and use the secret
      imagePullSecrets:
      - name: regcred
