apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 50051        # External gRPC port
      targetPort: 50051   # Port your gRPC server is listening on
      name: grpc
    - protocol: TCP
      port: 8080       # External HTTP port
      targetPort: 8080   # Port your HTTP server is listening on
      name: http
  type: NodePort
