apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80         # Port that will be exposed externally
    targetPort: 8080 # Port your container is listening on
  type: NodePort
