// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sql_db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserFcmToken struct {
	ID        int32
	UserID    int32
	FcmToken  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
