# Build stage
FROM golang:1.24 AS builder
WORKDIR /app

# Copy go.mod and go.sum and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy all source code
COPY . .

# Install Air for hot reloading in dev environment
RUN go install github.com/air-verse/air@latest

# Expose the application port (optional if you're using Docker Compose)
EXPOSE 8080

# Set the correct entrypoint to run the binary with air for hot-reloading
CMD ["air"]
